{
  try {
    doContextDestroyed();
  }
 catch (  Exception e) {
    _log.error(e,e);
  }
}
